name: Minify

on:
  push:
    branches: ["main"]

permissions:
  contents: write

jobs:
  minify:
    runs-on: ubuntu-latest
    steps:
      - name: check out the repository
        uses: actions/checkout@v4

      - name: minify the files
        uses: nizarmah/auto-minify@v3

      - name: commit the minified files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "bot: minified files"
  